---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argo
  name: id
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bacchus ID
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: id
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: top-level
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  source:
    repoURL: https://github.com/bacchus-snu/cd-manifests.git
    targetRevision: HEAD
    path: projects/id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
