resources:
  - statefulset.yaml
  - service.yaml
  - serviceaccount.yaml
  - vaultsecret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: snucse-back
      app.kubernetes.io/instance: snucse-back
      app.kubernetes.io/part-of: snucse
      app.kubernetes.io/component: backend
    includeSelectors: true

images:
  - name: snucse-back
    newName: ghcr.io/bacchus-snu/snucse-api
    newTag: v3.1.7
