---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: snucse-db-configs
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: snucse/config
  destination:
    create: true
    name: snucse-config
