---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: lab-vpn
  name: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: lab-vpn
  name: lab-vpn
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: lab-vpn/secret
  destination:
    create: true
    name: lab-vpn
