apiVersion: v1
kind: Service
metadata:
  namespace: lab-vpn
  name: lab-vpn
  labels:
    app.kubernetes.io/name: lab-vpn
    app.kubernetes.io/interface: lab-vpn
  annotations:
    # routed by the same external name as bacchus-vpn (vpn.bacchus.io)
    lbipam.cilium.io/ips: 10.89.0.32
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: lab-vpn
    app.kubernetes.io/interface: lab-vpn
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
