---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-20
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: intern-20
  namespace: intern-20
spec:
  parentRefs:
  - kind: Gateway
    name: web-gateway
    namespace: cilium-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/intern-20"
    backendRefs:
    - name: nginx
      namespace: intern-20
      port: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intern-20
  namespace: default
subjects:
- kind: Group
  name: intern-members@bacchus.io
roleRef:
  kind: Role
  name: intern-rbac
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: intern-20
  namespace: intern-20
spec:
  selector:
    instance: intern-rbac
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intern-20
  namespace: intern-20
  labels:
    instance: intern-rbac
spec:
  replicas: 3
  selector:
    matchLabels:
      instance: intern-rbac
  template:
    metadata:
      labels:
        instance: intern-rbac
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
