---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bacchus-bridge-configmap
  namespace: bacchus-bridge
data:
  matterbridge.toml: |
    [discord]
      [discord.bacchus]
      Server = "480254918343655454"
      AutoWebhooks = true
      RemoteNickFormat = "<{NICK}> "
      PreserveThreading = true

    [slack]
        [slack.waffle]
        RemoteNickFormat = "@{NICK}"
        PreserveThreading = true

    [[gateway]]
        name = "cse-contact"
        enable = true

        [[gateway.inout]]
        account = "discord.bacchus"
        channel = "cse-contact"

        [[gateway.inout]]
        account = "slack.waffle"
        channel = "team-cse-contact"

