---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bacchus-bridge
  name: bacchus-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacchus-bridge
  template:
    metadata:
      labels:
        app: bacchus-bridge
    spec:
      containers:
        - name: matterbridge
          image: 42wim/matterbridge:stable
          imagePullPolicy: IfNotPresent
          env:
            - name: MATTERBRIDGE_DISCORD_BACCHUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bacchus-bridge-config
                  key: discord-token
            - name: MATTERBRIDGE_SLACK_BACCHUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bacchus-bridge-config
                  key: slack-token
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: bacchus-bridge-config
              mountPath: /etc/matterbridge
      volumes:
        - name: bacchus-bridge-config
          configMap:
            name: bacchus-bridge-configmap
