---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cloudflared
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cloudflared
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/cloudflared
      kustomize: {}
