---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: sommelier-bacchus-sgs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sommelier
  destination:
    name: sommelier
    namespace: bacchus-sgs
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: v1.30
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: v1.30
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: v1.30
  ignoreDifferences:
    - group: sgs.snucse.org
      kind: WorkspaceSet
      name: sgs
      jsonPointers:
        - /metadata/annotations
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/sommelier/bacchus-sgs
      directory:
        include: 'resources.yaml'
    - repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
      targetRevision: 3.5.0
      chart: dcgm-exporter
      helm:
        values: |
          serviceMonitor:
            enabled: false
          nodeSelector:
            accelerator: nvidia-gpu
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 4.39.0
      chart: prometheus-node-exporter
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.25.1
      chart: kube-state-metrics
