---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs
---
apiVersion: v1
kind: Secret
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs
  annotations:
    kubernetes.io/service-account.name: bacchus-sgs
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bacchus-sgs
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - sgs.snucse.org
    resources:
      - workspacesets
    verbs:
      - get
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    resourceNames:
      - edit
    verbs:
      - bind
  - apiGroups:
      - ''
    resources:
      - limitranges
      - namespaces
      - resourcequotas
      - secrets
      - serviceaccounts
    verbs:
      - list
      - get
      - create
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - list
      - get
      - create
      - patch
      - delete
  # for monitoring
  - apiGroups:
      - ''
    resources:
      - endpoints
      - nodes
      - nodes/metrics
      - pods
      - services
    verbs:
      - list
      - get
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bacchus-sgs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bacchus-sgs
subjects:
  - kind: ServiceAccount
    name: bacchus-sgs
    namespace: bacchus-sgs
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspacesets.sgs.snucse.org
  labels:
    applyset.kubernetes.io/is-parent-type: 'true'
spec:
  scope: Cluster
  group: sgs.snucse.org
  names:
    plural: workspacesets
    singular: workspaceset
    kind: WorkspaceSet
    shortNames:
      - wss
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
---
apiVersion: sgs.snucse.org/v1
kind: WorkspaceSet
metadata:
  name: sgs
  labels:
    # ref: https://github.com/kubernetes/kubectl/blob/v0.30.0/pkg/cmd/apply/applyset.go#L169
    applyset.kubernetes.io/id: applyset-eGaq9sV3nwMTqoxoanOqvTcx-fUhHfmcx173gQrutHk-v1
  annotations:
    applyset.kubernetes.io/tooling: kubectl/v0.0.0
    applyset.kubernetes.io/contains-group-kinds: ''
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sgs-runtime-wrapper-installer
  namespace: bacchus-sgs
  labels:
    app.kubernetes.io/name: sgs-runtime-wrapper
    app.kubernetes.io/component: runtime-installer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sgs-runtime-wrapper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sgs-runtime-wrapper
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        nvidia.com/gpu.present: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      hostPID: true
      initContainers:
        - name: installer
          image: ghcr.io/bacchus-snu/sgs:latest
          command:
            - sh
            - -c
            - |
              set -e
              echo "Installing sgs-runtime-wrapper..."
              find /nix/store -name sgs-runtime-wrapper -executable -type f \
                -exec cp {} /host/usr/local/bin/sgs-runtime-wrapper \;
              chmod +x /host/usr/local/bin/sgs-runtime-wrapper
              echo "Installation complete. Verifying..."
              ls -l /host/usr/local/bin/sgs-runtime-wrapper

              # Hijack nvidia-container-runtime if present
              if [ -f /host/usr/bin/nvidia-container-runtime ] && [ ! -L /host/usr/bin/nvidia-container-runtime ]; then
                echo "Hijacking nvidia-container-runtime..."
                if [ ! -f /host/usr/bin/nvidia-container-runtime.real ]; then
                  mv /host/usr/bin/nvidia-container-runtime \
                     /host/usr/bin/nvidia-container-runtime.real
                fi
                ln -sf /usr/local/bin/sgs-runtime-wrapper \
                       /host/usr/bin/nvidia-container-runtime
                echo "Hijack complete. Verifying..."
                ls -la /host/usr/bin/nvidia-container-runtime*
              fi
          volumeMounts:
            - name: host-bin
              mountPath: /host/usr/bin
            - name: host-local-bin
              mountPath: /host/usr/local/bin
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
          resources:
            limits:
              cpu: 10m
              memory: 16Mi
            requests:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: host-bin
          hostPath:
            path: /usr/bin
            type: Directory
        - name: host-local-bin
          hostPath:
            path: /usr/local/bin
            type: Directory
