---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: gateway-api
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: gateway-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/atrium/gateway-api
      kustomize: {}
