---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: snucse
  name: snucse-sa
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  namespace: snucse
  name: snucse
spec:
  version: 8.4.12
  instances: 1
  baseServerId: 1000
  secretName: db-pw
  serviceAccountName: snucse-sa
  tlsUseSelfSigned: true
  router:
    instances: 1
    version: 8.4.10
  datadirVolumeClaimTemplate:
    storageClassName: rbd
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 20Gi
