serverVersion: 8.4.11
serverInstances: 1
routerInstances: 1
disableLookups: true

tls:
  useSelfSigned: true

credentials:
  root:
    secretName: db-pw

datadirVolumeClaimTemplate:
  storageClassName: rbd
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi

serverConfig:
  mycnf: |
    mysql_native_password=ON

