apiVersion: apps/v1
kind: Deployment
metadata:
  name: bacchus-vpn
spec:
  template:
    spec:
      initContainers:
        - name: sysctl-forward
          image: busybox:1.36
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1
          securityContext:
            privileged: true
        - name: envoy-patch
          image: bitnami/kubectl:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          command:
            # patch cilium-managed envoyconfig to remove grpc_web filter
            - /bin/bash
            - -c
            - |
                set -eux
                first_filter=$(kubectl get \
                  -n cilium-system \
                  ciliumenvoyconfigs.cilium.io cilium-gateway-web-gateway \
                  -ojsonpath='{$.spec.resources[0].filterChains[0].filters[0].typedConfig.httpFilters[0].name}')
                [[ "$first_filter" = "envoy.filters.http.grpc_web" ]] || exit 0
                kubectl patch \
                  -n cilium-system \
                  --type=json \
                  ciliumenvoyconfigs.cilium.io/cilium-gateway-web-gateway \
                  -p '[{"op":"remove","path":"/spec/resources/0/filterChains/0/filters/0/typedConfig/httpFilters/0"},{"op":"remove","path":"/spec/resources/0/filterChains/1/filters/0/typedConfig/httpFilters/0"}]'
      containers:
        - name: app
          image: wg-access-server # replaced by kustomize
          ports:
            - name: http
              containerPort: 8000
            - protocol: UDP
              containerPort: 51820
          env:
            - name: WG_CONFIG
              value: /config.yaml
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: config
              subPath: config.yaml
              mountPath: /config.yaml
              readOnly: true
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
              drop:
                - ALL
            readOnlyRootFilesystem: true
            #runAsNonRoot: true
            #runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: bacchus-vpn
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: config
          secret:
            secretName: bacchus-vpn-config
        - name: data
          persistentVolumeClaim:
            claimName: bacchus-vpn-data
