apiVersion: apps/v1
kind: Deployment
metadata:
  name: bacchus-vpn
spec:
  template:
    spec:
      initContainers:
        - name: sysctl-forward
          image: busybox:1.36
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1
          securityContext:
            privileged: true
      containers:
        - name: app
          image: wg-access-server # replaced by kustomize
          ports:
            - name: http
              containerPort: 8000
            - protocol: UDP
              containerPort: 51820
          env:
            - name: WG_CONFIG
              value: /config.yaml
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: config
              subPath: config.yaml
              mountPath: /config.yaml
              readOnly: true
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
              drop:
                - ALL
            readOnlyRootFilesystem: true
            #runAsNonRoot: true
            #runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: config
          secret:
            secretName: bacchus-vpn-config
        - name: data
          persistentVolumeClaim:
            claimName: bacchus-vpn-data
