serverVersion: 8.4.11
serverInstances: 1
routerInstances: 1
disableLookups: true

tls:
  useSelfSigned: true

credentials:
  root:
    secretName: cloudstack-db

datadirVolumeClaimTemplate:
  storageClassName: rbd
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi

serverConfig:
  mycnf: |
    innodb-rollback-on-timeout=1
    innodb-lock-wait-timeout=600
    max-connections=350
    log-bin=mysql-bin
    binlog-format=ROW

