installCRDs: true
enableCertificateOwnerRef: true
resources:
 requests:
   cpu: 100m
   memory: 128Mi
 limits:
   cpu: 100m
   memory: 128Mi
extraArgs:
  - --feature-gates=ExperimentalGatewayAPISupport=true

