dex:
  enabled: false
configs:
  cm:
    admin.enabled: false
    oidc.config: |
      name: Bacchus
      issuer: https://dev-1p1l3bz6kxwkga5k.us.auth0.com/
      clientID: CEqYFMXA6A5SIQvxNdX8CgqBVHKhuxit
      clientSecret: $oidc-auth:clientSecret
      requestedScopes: [openid, profile, email]
    url: https://argocd.bacchus.io
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil and obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
      return hs
  params:
    server.insecure: true
  rbac:
    scopes: '[https://bacchus.io/groups]'
    policy.csv: |
      g, regular-members@bacchus.snucse.org, role:admin
    policy.default: role:readonly

  secret:
    createSecret: false

controller:
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 1Gi
