---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: v1.28
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: v1.28
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: v1.28
  ignoreDifferences:
    # Patched by metallb
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.13.12
      chart: metallb
      helm:
        valueFiles:
          - $values/foundation/argo/metallb/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: feat/talos
      ref: values
