---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: id-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: id-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/atrium/id-dev
    - repoURL: https://valkey.io/valkey-helm/
      targetRevision: 0.12.0
      chart: valkey
      helm:
        valueFiles:
          - $values/argocd/atrium/id-dev/valkey-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
