---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: gateway-api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: gateway-system
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: foundation/argo/gateway-api
      kustomize: {}
