---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: id
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: id
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: foundation/argo/id
      kustomize: {}
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 18.9.1
      chart: redis
      helm:
        valueFiles:
          - $values/foundation/argo/argocd/redis-values.yaml
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.1.0
      chart: postgresql
      helm:
        valueFiles:
          - $values/foundation/argo/argocd/postgresql-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
