---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metrics-server
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.14.0
      chart: metrics-server
      helm:
        valueFiles:
          - $values/argocd/atrium/metrics-server/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
