---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bacchus-sgs-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: bacchus-sgs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/bacchus-sgs-monitoring
      kustomize: {}
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.3.1
      chart: grafana
      helm:
        valueFiles:
          - $values/argocd/waiter/bacchus-sgs-monitoring/grafana-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
