---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-prometheus
spec:
  scrapeInterval: 1m
  evaluationInterval: 1m
  scrapeConfigSelector:
    matchLabels:
      app.kubernetes.io/name: bacchus-sgs-monitoring
      app.kubernetes.io/instance: bacchus-sgs-monitoring
  ruleSelector:
    matchLabels:
      app.kubernetes.io/name: bacchus-sgs-monitoring
      app.kubernetes.io/instance: bacchus-sgs-monitoring
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  enableFeatures:
    # resources
    - auto-gomaxprocs
    - auto-gomemlimit
    # sort_by_label
    - promql-experimental-functions
  retention: 30d
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOncePod
        resources:
          requests:
            storage: 100Gi
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-kubelet
spec:
  kubernetesSDConfigs:
    - apiServer: https://sommelier.snucse.org:6443
      tlsConfig:
        ca:
          secret:
            name: bacchus-sgs-sommelier-creds
            key: ca.crt
      authorization:
        credentials:
          name: bacchus-sgs-sommelier-creds
          key: token
      role: node
  scheme: HTTPS
  tlsConfig:
    ca:
      secret:
        name: bacchus-sgs-sommelier-creds
        key: ca.crt
    # NOTE: sketchy af
    insecureSkipVerify: true
  authorization:
    type: Bearer
    credentials:
      name: bacchus-sgs-sommelier-creds
      key: token
  metricsPath: /metrics/resource
  relabelings:
    - action: replace
      sourceLabels:
        - instance
      targetLabel: node
    - action: replace
      targetLabel: job
      replacement: kubelet
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-node-exporter
spec:
  kubernetesSDConfigs:
    - apiServer: https://sommelier.snucse.org:6443
      tlsConfig:
        ca:
          secret:
            name: bacchus-sgs-sommelier-creds
            key: ca.crt
      authorization:
        credentials:
          name: bacchus-sgs-sommelier-creds
          key: token
      role: endpoints
      namespaces:
        names:
          - bacchus-sgs
  proxyUrl: http://10.91.0.20:3128
  relabelings:
    - action: keep
      sourceLabels:
        - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
        - __meta_kubernetes_service_label_app_kubernetes_io_name
        - __meta_kubernetes_endpoint_port_name
      regex: true;prometheus-node-exporter;metrics
    - sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: node
    - action: replace
      targetLabel: job
      replacement: node-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-kube-state-metrics
spec:
  kubernetesSDConfigs:
    - apiServer: https://sommelier.snucse.org:6443
      tlsConfig:
        ca:
          secret:
            name: bacchus-sgs-sommelier-creds
            key: ca.crt
      authorization:
        credentials:
          name: bacchus-sgs-sommelier-creds
          key: token
      role: endpoints
      namespaces:
        names:
          - bacchus-sgs
  proxyUrl: http://10.91.0.20:3128
  relabelings:
    - action: keep
      sourceLabels:
        - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
        - __meta_kubernetes_service_label_app_kubernetes_io_name
        - __meta_kubernetes_endpoint_port_name
      regex: true;kube-state-metrics;http
    - action: replace
      targetLabel: job
      replacement: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-dcgm-exporter
spec:
  kubernetesSDConfigs:
    - apiServer: https://sommelier.snucse.org:6443
      tlsConfig:
        ca:
          secret:
            name: bacchus-sgs-sommelier-creds
            key: ca.crt
      authorization:
        credentials:
          name: bacchus-sgs-sommelier-creds
          key: token
      role: endpoints
      namespaces:
        names:
          - bacchus-sgs
  proxyUrl: http://10.91.0.20:3128
  relabelings:
    - action: keep
      sourceLabels:
        - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
        - __meta_kubernetes_service_label_app_kubernetes_io_name
        - __meta_kubernetes_endpoint_port_name
      regex: true;dcgm-exporter;metrics
    - sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: node
    - action: replace
      targetLabel: job
      replacement: dcgm-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: bacchus-sgs
  name: bacchus-sgs-resources
  labels:
    app.kubernetes.io/name: bacchus-sgs-monitoring
    app.kubernetes.io/instance: bacchus-sgs-monitoring
spec:
  groups:
    - name: bacchus-sgs-resources/allocation
      rules:
        - record: sgs:node_resource:capacity
          expr: |
            sum by (node, resource) (
              kube_node_status_capacity{node!~"control-.*",resource=~"cpu|memory|nvidia_com_gpu"}
            )
        - record: sgs:node_namespace_resource:allocated
          expr: |
            sum by (node, resource, namespace) (
                kube_pod_container_resource_requests{namespace=~"ws-.*",resource=~"cpu|memory|nvidia_com_gpu"}
              * on (pod) group_left ()
                kube_pod_status_phase{phase="Running"}
            )
        - record: sgs:node_resource:unallocated
          expr: |2
                sum by (node, resource) (
                  kube_node_status_allocatable{node!~"control-.*",resource=~"cpu|memory|nvidia_com_gpu"}
                )
              -
                sum by (node, resource) (
                  kube_pod_container_resource_requests * on (pod) group_left () kube_pod_status_phase{phase="Running"}
                )
            or
              sum by (node, resource) (
                kube_node_status_allocatable{node!~"control-.*",resource=~"cpu|memory|nvidia_com_gpu"}
              )
    - name: bacchus-sgs-resources/use
      rules:
        - record: sgs:node_namespace_resource:used
          labels:
            resource: cpu
          expr: |
            sum by (node, namespace) (rate(container_cpu_usage_seconds_total{namespace=~"ws-.*"}[5m]))
        - record: sgs:node_namespace_resource:used
          labels:
            resource: memory
          expr: |
            sum by (node, namespace) (container_memory_working_set_bytes{namespace=~"ws-.*"})
        - record: sgs:node_namespace_resource:used
          labels:
            resource: nvidia_com_gpu
          expr: |
            sum by (node, namespace) (clamp_max(DCGM_FI_DEV_GPU_UTIL{namespace=~"ws-.*"}, 1))
        - record: sgs:node_resource:unused
          labels:
            resource: cpu
          expr: |
            sum by (node) (rate(node_cpu_seconds_total{mode="idle",node!~"control-.*"}[5m]))
        - record: sgs:node_resource:unused
          labels:
            resource: memory
          expr: |
            sum by (node) (node_memory_MemAvailable_bytes{node!~"control-.*"})
        - record: sgs:node_resource:unused
          labels:
            resource: nvidia_com_gpu
          expr: |
            sum by (node) (1 - clamp_max(DCGM_FI_DEV_GPU_UTIL, 1))
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bacchus-sgs-monitoring
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: bacchus-sgs/monitoring
  destination:
    create: true
    name: bacchus-sgs-monitoring
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bacchus-sgs-monitoring
spec:
  hostnames:
    - sgs-dashboard.snucse.org
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-snucse-org
  rules:
    - backendRefs:
        - name: bacchus-sgs-monitoring-grafana
          port: 80
