---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bacchus-sgs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: bacchus-sgs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/bacchus-sgs
      kustomize: {}
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 15.5.10
      chart: postgresql
      helm:
        valueFiles:
          - $values/argocd/waiter/bacchus-sgs/postgresql-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
