---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ferrari-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ferrari
  destination:
    name: ferrari
    namespace: gpu-operator
  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      targetRevision: 23.3.2
      chart: gpu-operator
      helm:
        values: |
          mig:
            strategy: mixed
          toolkit:
            env:
              - name: CONTAINERD_CONFIG
                value: /etc/k0s/containerd.toml
              - name: CONTAINERD_SOCKET
                value: /run/k0s/containerd.sock
          # also need to manually patch dcgm-exporter DS to add env
          # DCGM_EXPORTER_KUBERNETES_GPU_ID_TYPE=uid
