---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: vault
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.27.0
      chart: vault
      helm:
        valueFiles:
          - $values/argocd/waiter/vault/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/vault
      directory:
        include: 'resources.yaml'
