---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: vault
  name: vault-active
spec:
  parentRefs:
    - namespace: cilium-system
      name: internal-web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - vault.internal.bacchus.io
  rules:
    - backendRefs:
        - name: vault-active
          port: 8200
---
# In case of vault failure (all replicas down/sealed) and Dex failure
# We may not have easy access to the Kubernetes API externally before Vault becomes ready again.
# This host allows administrators to access the Vault UI to unseal at least one replica.
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: vault
  name: vault-any
spec:
  parentRefs:
    - namespace: cilium-system
      name: internal-web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - vault-any.internal.bacchus.io
  rules:
    - backendRefs:
        - name: vault-ui
          port: 8200
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vault
  name: vault-raft-snapshot
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: vault
  name: vault-raft-snapshot
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault-raft-snapshot
          restartPolicy: Never
          initContainers:
            - name: create-vault-raft-snapshot
              image: hashicorp/vault:1.17.2
              volumeMounts:
                - name: scratch
                  mountPath: /scratch
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
              command:
                - /bin/sh
                - -c
                - |
                    export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login jwt=@/var/run/secrets/kubernetes.io/serviceaccount/token role=vault-raft-snapshot)
                    vault operator raft snapshot save /scratch/vault.snap
          containers:
            - name: backup
              image: ghcr.io/bacchus-snu/images/proxmox-backup-client:5575324
              envFrom:
                - secretRef:
                    name: vault-raft-snapshot-pbs
              volumeMounts:
                - name: scratch
                  mountPath: /scratch
              resources:
                requests:
                  cpu: 100m
                  memory: 1Gi
                limits:
                  cpu: 100m
                  memory: 1Gi
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              args: ['backup', '--ns=waiter', '--backup-id=vault', '--backup-type=ct', 'vault.pxar:/scratch']
