server:
  resources:
    requests:
      memory: 512Mi
      cpu: 1
    limits:
      memory: 512Mi

  auditStorage:
    enabled: true

ui:
  enabled: true

injector:
  enabled: false
speaker:
  tolerateMaster: false
