replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: dex
        app.kubernetes.io/instance: dex
    matchLabelKeys:
      - pod-template-hash
    topologyKey: kubernetes.io/hostname
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

envVars:
  - name: GOOGLE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: dex-google-secret
        key: GOOGLE_CLIENT_ID
  - name: GOOGLE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: dex-google-secret
        key: GOOGLE_CLIENT_SECRET
  - name: GOOGLE_SERVICE_ACCOUNT
    value: /secret/service-account.json

  - name: DEX_CLIENT_BACCHUS_BARTENDER
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-bartender
  - name: DEX_CLIENT_BACCHUS_VAULT
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-vault
  - name: DEX_CLIENT_BACCHUS_ARGOCD
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-argocd
  - name: DEX_CLIENT_BACCHUS_GRAFANA
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-grafana
  - name: DEX_CLIENT_BACCHUS_SGS_DASHBOARD
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-sgs-monitoring
  - name: DEX_CLIENT_BACCHUS_VPN
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-vpn
  - name: DEX_CLIENT_BACCHUS_HOWTO
    valueFrom:
      secretKeyRef:
        name: dex-client-secrets
        key: bacchus-howto

volumes:
  - name: dex-google-secret
    secret:
      secretName: dex-google-secret
      items:
        - key: GOOGLE_SERVICE_ACCOUNT
          path: service-account.json

volumeMounts:
  - name: dex-google-secret
    mountPath: /secret

podSecurityContext:
  fsGroup: 1337

config:
  issuer: https://auth.bacchus.io/dex
  storage:
    type: kubernetes
    config:
      inCluster: true
  oauth2:
    skipApprovalScreen: true

  staticClients:
    - name: Waiter
      id: bacchus-waiter
      public: true
    - name: Bartender
      id: bacchus-bartender
      redirectURIs:
        - https://fizz.snucse.org:8006
        - https://gin.snucse.org:8006
        - https://ramos.snucse.org:8006
      secretEnv: DEX_CLIENT_BACCHUS_BARTENDER
    - name: Vault
      id: bacchus-vault
      redirectURIs:
        - https://vault.internal.bacchus.io/ui/vault/auth/oidc/oidc/callback
        - http://localhost:8250/oidc/callback
      secretEnv: DEX_CLIENT_BACCHUS_VAULT
    - name: ArgoCD
      id: bacchus-argocd
      redirectURIs:
        - https://argocd.internal.bacchus.io/auth/callback
      secretEnv: DEX_CLIENT_BACCHUS_ARGOCD
    - name: Grafana
      id: bacchus-grafana
      redirectURIs:
        - https://dashboard.internal.bacchus.io/login/generic_oauth
      secretEnv: DEX_CLIENT_BACCHUS_GRAFANA
    - name: Bacchus SGS Dashboard
      id: bacchus-sgs-monitoring
      redirectURIs:
        - https://sgs-dashboard.snucse.org/login/generic_oauth
      secretEnv: DEX_CLIENT_BACCHUS_SGS_DASHBOARD
    - name: Bacchus VPN
      id: bacchus-vpn
      redirectURIs:
        - https://vpn.bacchus.io/callback
      secretEnv: DEX_CLIENT_BACCHUS_VPN
    - name: Bacchus Howto
      id: bacchus-howto
      redirectURIs:
        - https://howto.bacchus.io/oauth2/callback
        - https://test-howto.bacchus.io/oauth2/callback
      secretEnv: DEX_CLIENT_BACCHUS_HOWTO

  connectors:
    - name: Google
      id: google
      type: google
      config:
        issuer: https://accounts.google.com
        clientID: $GOOGLE_CLIENT_ID
        clientSecret: $GOOGLE_CLIENT_SECRET
        redirectURI: https://auth.bacchus.io/dex/callback
        hostedDomains:
          - bacchus.snucse.org
        serviceAccountFilePath: $GOOGLE_SERVICE_ACCOUNT
        domainToAdminEmail:
          "*": admin@snucse.org
