---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: sommelier-cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # needed to prevent permanent diff with ServerSideApply
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: sommelier
  destination:
    name: sommelier
    namespace: cilium-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # CRDs are too large for client-side apply
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: v1.29
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: v1.29
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: v1.29
  ignoreDifferences:
    # Patched by cilium
    - kind: Secret
      name: cilium-ca
      jsonPointers:
        - /data
    - kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data
    - kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data
  sources:
    - repoURL: https://helm.cilium.io/
      targetRevision: 1.16.1
      chart: cilium
      helm:
        valueFiles:
          - $values/argocd/sommelier/cilium/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/sommelier/cilium
      directory:
        include: 'resources.yaml'
