# ref: https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/
ipam:
  mode: kubernetes
cgroup:
  # non-talos hosts require autoMount
  # fortunately, it doesn't break anything
  #autoMount:
  #  enabled: true
  hostRoot: /sys/fs/cgroup
securityContext:
  capabilities:
    cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
    ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]

operator:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ''
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: null

# replace kube-proxy
kubeProxyReplacement: true
k8sServiceHost: sommelier.snucse.org
k8sServicePort: 6443

# enable l2 announcements
l2announcements:
  enabled: true

# l2 announcements lead to higher qps
# ref: https://docs.cilium.io/en/latest/network/l2-announcements/
k8sClientRateLimit:
  qps: 10
  burst: 20

# enable hubble
hubble:
  relay:
    enabled: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
  ui:
    enabled: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: ''
