---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: sommelier-http-proxy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sommelier
  destination:
    name: sommelier
    namespace: http-proxy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/sommelier/http-proxy
      kustomize: {}
