---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: rbd
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: c3e392bd-8ab1-44b3-ab97-9b964c28bf18
  pool: kubernetes
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/snapshotter-secret-name:  csi-rbd-secret
