apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-vpn
  name: lab-vpn
  labels:
    app.kubernetes.io/name: lab-vpn
    app.kubernetes.io/interface: lab-vpn
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lab-vpn
      app.kubernetes.io/interface: lab-vpn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab-vpn
        app.kubernetes.io/interface: lab-vpn
    spec:
      initContainers:
        - name: sysctl-forward
          image: busybox:1.36
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1
          securityContext:
            privileged: true
      containers:
        - name: app
          image: ghcr.io/bacchus-snu/lab-vpn:latest
          command:
            - sh
            - -c
            - 'wg-quick up /secrets/wg-lab.conf && sleep inf'
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 51820
              protocol: UDP
          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: /secrets
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ip link show wg-lab >/dev/null
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ip link show wg-lab >/dev/null
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: secrets
          secret:
            secretName: lab-vpn
            defaultMode: 0o400
