---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vault-secrets-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: vault-secrets-operator
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.4.3
      chart: vault-secrets-operator
      helm:
        valueFiles:
          - $values/foundation/argo/vso/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
