---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: warpgate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: warpgate
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/warpgate
      kustomize: {}
