resources:
  - resources.yaml

labels:
  - pairs:
      app.kubernetes.io/name: warpgate
      app.kubernetes.io/instance: warpgate
    includeTemplates: true

configMapGenerator:
  - name: warpgate-config
    files:
      - warpgate.yaml

images:
  - name: warpgate
    newName: ghcr.io/warp-tech/warpgate
    newTag: 0.28.6
