resources:
  - statefulset.yaml
  - service.yaml
  - serviceaccount.yaml
  - vaultsecret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: snucse-db
      app.kubernetes.io/instance: snucse-db
      app.kubernetes.io/part-of: snucse
      app.kubernetes.io/component: db
    includeSelectors: true

images:
  - name: snucse-db
    newName: mysql
    newTag: 5.7
