---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snucse-db
spec:
  serviceName: snucse-db
  template:
    spec:
      containers:
        - name: app
          image: mysql:5.7
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "snucse_production"
          envFrom:
          - secretRef:
              name: db-pw
          ports:
            - name: http
              containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes:
        - ReadWriteOncePod
      resources:
        requests:
          storage: 10Gi
