---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-pw
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: snucse/db
  destination:
    create: true
    name: db-pw
