---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: id-core-config
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: id/core/config
  destination:
    create: true
    name: id-core-config
