auth:
  username: snucse
  database: snucse_production
  existingSecret: db-pw

primary:
  extraFlags: "--default-authentication-plugin=mysql_native_password"
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1024Mi
