auth:
  username: snucse
  database: snucse_production
  existingSecret: db-pw
  authenticationPolicy: "mysql_native_password"

primary:
  extraFlags: "--mysql-native-password=ON"
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1024Mi
