---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: csi-snapshot
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: kube-system
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: v6.3.3
      path: client/config/crd
      kustomize: {}
    - repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
      targetRevision: v6.3.3
      path: deploy/kubernetes/snapshot-controller
      kustomize: {}
