---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bacchus-howto
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: bacchus-howto
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # managedNamespaceMetadata:
    #   labels:
    #     pod-security.kubernetes.io/enforce: baseline
    #     pod-security.kubernetes.io/enforce-version: latest
    #     pod-security.kubernetes.io/warn: baseline
    #     pod-security.kubernetes.io/warn-version: latest
    #     pod-security.kubernetes.io/audit: baseline
    #     pod-security.kubernetes.io/audit-version: latest
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/bacchus-howto
      kustomize: {}
    - repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 7.7.9
      chart: oauth2-proxy
      helm:
        valueFiles:
                - $values/argocd/waiter/bacchus-howto/howto-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values



      
