{
 "title": "SNUCSE GPU Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"gpu-kube-state-metrics\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Overview - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=~\"$instance\"}\n    -\nnode_boot_time_seconds{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode!=\"idle\"}[$__rate_interval]))\n    /\nsum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nnode_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    /\nnode_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nnode_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}\n    /\nnode_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "zpool Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\nmax(node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", device=\"zpool\"})\n    /\nmin(node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", device=\"zpool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Util",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{job=\"gpu-dcgm-exporter\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vCPU Allocatable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"})\n    -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"}) by (namespace, pod)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocatable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"})\n    -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"}) by (namespace, pod)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Allocatable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode!=\"idle\"}[$__rate_interval])) by (mode)\n    / ignoring (mode) group_left()\nsum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode=\"idle\"}[$__rate_interval]))\n    /\nsum(rate(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    -\nnode_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    -\nnode_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    -\nnode_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    -\nnode_memory_SReclaimable_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    +\nnode_memory_Buffers_bytes{job=\"node-exporter\", instance=~\"$instance\"}\n    +\nnode_memory_SReclaimable_bytes{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "Cache + Buffer"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\nnode_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}\n    /\nnode_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", mountpoint=\"/\"}",
     "legendFormat": "RootFS"
    },
    {
     "expr": "1 -\nmax(node_filesystem_avail_bytes{job=\"node-exporter\", instance=~\"$instance\", device=\"zpool\"})\n    /\nmin(node_filesystem_size_bytes{job=\"node-exporter\", instance=~\"$instance\", device=\"zpool\"})",
     "legendFormat": "zpool"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device=~\"ens.*\"}[$__rate_interval])) by (device) > 0",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device=~\"ens.*\"}[$__rate_interval])) by (device) > 0",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "hwmon Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(node_hwmon_power_average_watt{job=\"node-exporter\", instance=~\"$instance\"}) by (chip, sensor)",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "hwmon Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(node_hwmon_temp_celsius{job=\"node-exporter\", instance=~\"$instance\"}) by (chip, sensor)\n    * on (chip) group_left(chip_name)\nnode_hwmon_chip_names{job=\"node-exporter\", instance=~\"$instance\"}\n    * on (chip, sensor) group_left(label)\nnode_hwmon_sensor_label{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "{{chip_name}} {{label}}"
    }
   ]
  },
  {
   "title": "DCGM GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{job=\"gpu-dcgm-exporter\", instance=~\"$instance\"}) by (gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{job=\"gpu-dcgm-exporter\", instance=~\"$instance\"}) by (gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_TEMP{job=\"gpu-dcgm-exporter\", instance=~\"$instance\"}) by (gpu)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Kubernetes - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"}) by (namespace, pod)\n) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"})\n    -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"cpu\"}) by (namespace, pod)\n)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"}) by (namespace, pod)\n) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"})\n    -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"memory\"}) by (namespace, pod)\n)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) -\nsum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total GPU-Hours",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n    ) by (namespace) [24h:1m]\n) * 60 > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(\n    sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n    ) by (namespace) [1w:1m]\n) * 60 > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time(\n    sum(\n    kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Running\"}\n        * on (namespace, pod)\n    sum(kube_pod_container_resource_requests{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n    ) by (namespace) [30d:1m]\n) * 60 > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Pending\"}[24h:1m])) by (namespace, pod)\n  * on (namespace, pod)\n(kube_pod_status_phase{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", phase=\"Pending\"} > 0)\n* 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.cpu\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.cpu\", type=\"used\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.cpu\", type=\"used\"}) by (namespace)\n    /\nsum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.cpu\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.memory\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.memory\", type=\"used\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.memory\", type=\"used\"}) by (namespace)\n    /\nsum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.memory\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.nvidia.com/gpu\", type=\"used\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.nvidia.com/gpu\", type=\"used\"}) by (namespace)\n    /\nsum(kube_resourcequota{job=\"gpu-kube-state-metrics\", instance=~\"$instance\", resource=\"requests.nvidia.com/gpu\", type=\"hard\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wasted GPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)\n    -\n(count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} > 10) by (namespace))\n    or\nsum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total Wasted GPU-Hours",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum_over_time((sum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)\n    -\n(count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} > 10) by (namespace))\n    or\nsum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace))[24h:1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time((sum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)\n    -\n(count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} > 10) by (namespace))\n    or\nsum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace))[1w:1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum_over_time((sum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)\n    -\n(count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} > 10) by (namespace))\n    or\nsum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace))[30d:1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 -\nsum_over_time(count(DCGM_FI_DEV_GPU_UTIL{namespace!=\"\"} > 10) by (namespace)[1w:1m])\n    /\nsum_over_time(sum(\n    sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (namespace, pod)\n        * on (namespace, pod)\n    sum(kube_pod_status_phase{phase=\"Running\", job=\"gpu-kube-state-metrics\"}) by (namespace, pod)\n) by (namespace)[1w:1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}