---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: gpu-monitoring
  name: gpu-kube-state-metrics
  labels:
    release: dashboard
spec:
  metricsPath: /kube-state/metrics
  staticConfigs:
    - labels:
        job: gpu-kube-state-metrics
      targets:
        - ferrari.snucse.org:30080
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: gpu-monitoring
  name: gpu-node-exporter
  labels:
    release: dashboard
spec:
  metricsPath: /node-exporter/metrics
  staticConfigs:
    # use the same label as the in-cluster node-expoter, as node-exporter only
    # has node-level metrics and thus the metrics cannot collide with
    # in-cluster nodes
    - labels:
        job: node-exporter
      targets:
        - ferrari.snucse.org:30080
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  namespace: gpu-monitoring
  name: gpu-dcgm-exporter
  labels:
    release: dashboard
spec:
  metricsPath: /dcgm-exporter/metrics
  staticConfigs:
    - labels:
        job: gpu-dcgm-exporter
      targets:
        - ferrari.snucse.org:30080
