---
apiVersion: v1
kind: Service
metadata:
  name: snucse-elasticsearch
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9200
      targetPort: http
    - name: transport
      port: 9300
      targetPort: transport
