---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: intern-rbac
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: foundation/argo/intern-rbac
      directory:
        include: 'resources.yaml'
