---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  namespace: default
  name: talos-api-access-talos-secrets
spec:
  roles:
    - os:etcd:backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: talos-etcd-snapshots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: talos-etcd-snapshots
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: talos-secrets
              secret:
                secretName: talos-api-access-talos-secrets
            - name: snapshots
              persistentVolumeClaim:
                claimName: talos-etcd-snapshots
          containers:
            - name: app
              image: alpine:3
              volumeMounts:
                - name: talos-secrets
                  mountPath: /var/run/secrets/talos.dev
                  readOnly: true
                - name: snapshots
                  mountPath: /snapshots
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
              command:
                - /bin/sh
                - -c
                - |
                    set -euox
                    wget -O /tmp/talosctl https://github.com/siderolabs/talos/releases/download/v1.6.1/talosctl-linux-amd64
                    chmod +x /tmp/talosctl
                    /tmp/talosctl -n 10.89.0.21 etcd snapshot /snapshots/$(date -uIsecond)-db.snapshot
          securityContext:
            fsGroup: 1337
