---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: web-gateway
spec:
  blocks:
    - cidr: 10.89.0.30/32
    - cidr: 10.89.0.31/32
    - cidr: 10.89.0.32/32
    - cidr: 10.89.0.33/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: web-gateway
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  loadBalancerIPs: true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  namespace: cilium-system
  name: web-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: ECDSA
    external-dns.alpha.kubernetes.io/target: waiter.bacchus.io
  labels:
    external-dns.alpha.kubernetes.io/include: "true"
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 10.89.0.30
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-snucse-org
      protocol: HTTPS
      port: 443
      hostname: "*.snucse.org"
      tls:
        certificateRefs:
          - name: web-gateway-certs
      allowedRoutes:
        namespaces:
          from: All
    - name: https-bacchus-io
      protocol: HTTPS
      port: 443
      hostname: "*.bacchus.io"
      tls:
        certificateRefs:
          - name: web-gateway-certs
      allowedRoutes:
        namespaces:
          from: All
    - name: https-cse
      protocol: HTTPS
      port: 443
      hostname: "cse.snu.ac.kr"
      tls:
        certificateRefs:
          - name: web-gateway-cse-cert
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  namespace: cilium-system
  name: internal-web-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/private-key-algorithm: ECDSA
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 10.89.0.33
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-bacchus-io
      protocol: HTTPS
      port: 443
      hostname: "*.internal.bacchus.io"
      tls:
        certificateRefs:
          - name: internal-web-gateway-certs
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cilium-system
  name: web-gateway-https-redirect
  annotations:
    # Otherwise, external-dns creates a wildcard record
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  parentRefs:
    - name: web-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cilium-system
  name: internal-web-gateway-https-redirect
spec:
  parentRefs:
    - name: internal-web-gateway
      sectionName: http
    - name: web-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
