# ref: https://www.talos.dev/v1.6/kubernetes-guides/network/deploying-cilium/
ipam:
  mode: kubernetes
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
securityContext:
  capabilities:
    cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
    ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]

operator:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: null
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists

# replace kube-proxy
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445

# enable l2 announcements
l2announcements:
  enabled: true

# l2 announcements lead to higher qps
# ref: https://docs.cilium.io/en/latest/network/l2-announcements/
k8sClientRateLimit:
  qps: 10
  burst: 20

# enable gateway
gatewayAPI:
  enabled: true
  # required for h2
  enableAlpn: true

# enable hubble
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
