---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: id-db
spec:
  destination:
    namespace: id
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.2
    chart: postgresql
    helm:
      values: |
        auth:
          username: id
          database: id
          existingSecret: id-core-config
          secretKeys:
            userPasswordKey: db-password
            adminPasswordKey: db-admin-password
            replicationPasswordKey: db-replication-password
  project: id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
