---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-{}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: intern-{}
  namespace: intern-{}
spec:
  hostnames:
  - 'practice.bacchus.io'
  parentRefs:
  - kind: Gateway
    name: web-gateway
    namespace: cilium-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/intern-{}"
    backendRefs:
    - name: practice
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: "/"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intern-{}
  namespace: intern-{}
subjects:
- kind: Group
  name: intern-members@bacchus.snucse.org
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: intern-{}
  namespace: intern-{}
spec:
  selector:
    instance: intern-rbac
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intern-{}
  namespace: intern-{}
  labels:
    instance: intern-rbac
spec:
  replicas: 3
  selector:
    matchLabels:
      instance: intern-rbac
  template:
    metadata:
      labels:
        instance: intern-rbac
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
