# looser restrictions, as regular users will be accessing our cluster
cluster:
  apiServer:
    extraArgs:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: baseline
            audit-version: latest
            enforce: baseline
            enforce-version: latest
            warn: baseline
            warn-version: latest
          kind: PodSecurityConfiguration
