---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: testing
  name: hello
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  source:
    repoURL: https://github.com/bacchus-snu/cd-manifests.git
    targetRevision: HEAD
    path: projects/testing/hello
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
