---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: top-level
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/bacchus-snu/cd-manifests.git
    targetRevision: main
    path: argocd/waiter
    directory:
      recurse: true
      include: '*/app.yaml'
