auth:
  username: id
  database: id
  existingSecret: id-dev-db-creds

primary:
  initdb:
    scriptsConfigMap: id-dev-db-schema
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

# Override the default image to use the legacy repository due to Bitnami policy change
image:
  registry: docker.io
  repository: bitnamilegacy/postgresql