---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: id-dev
  name: id
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - id-dev.bacchus.io
  rules:
    # default route to frontend
    - backendRefs:
        - name: id-front
          port: 80
    # backend routes
    - backendRefs:
        - name: id-core
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /o
        - path:
            type: Exact
            value: /Authentication/Login.aspx
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: id-dev
  name: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: id-dev-db-creds
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: id-dev/db/creds
  destination:
    create: true
    name: id-dev-db-creds
