engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

localpv-provisioner:
  hostpathClass:
    xfsQuota:
      enabled: true
  localpv:
    basePath: /var/data
    # schedule provisioners on control-plane nodes
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
