# Use volume mounts instead
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nvidia-container-toolkit
configFiles:
    - mountPath: /usr/local/etc/nvidia-container-runtime/config.toml
      content: |
        disable-require = false
        accept-nvidia-visible-devices-envvar-when-unprivileged = false
        accept-nvidia-visible-devices-as-volume-mounts = true

        [nvidia-container-cli]
        #root = "/run/nvidia/driver"
        #path = "/usr/bin/nvidia-container-cli"
        environment = []
        debug = "/var/log/nvidia-container-cli.log"
        ldcache = "/usr/local/glibc/etc/ld.so.cache"
        ldconfig = "@/usr/local/glibc/sbin/ldconfig"
        load-kmods = false
        user = "0:0"
        #no-cgroups = false

        [nvidia-container-runtime]
        debug = "/var/log/nvidia-container-runtime.log"
