---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bacchus-regular-members
subjects:
  - kind: Group
    name: regular-members@bacchus.snucse.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bacchus-intern-members
subjects:
  - kind: Group
    name: intern-members@bacchus.snucse.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
