image:
  tag: v0.14.0

provider: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: CF_API_TOKEN

sources:
  - gateway-httproute

domainFilters:
  - snucse.org
  - bacchus.io

extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)

txtOwnerId: waiter
policy: sync
