apiVersion: apiserver.config.k8s.io/v1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://id.snucse.org/o
      audiences:
        - kubernetes-oidc
    claimMappings:
      username:
        claim: username
        prefix: "id:"
      groups:
        claim: groups
        prefix: "id:"
  - issuer:
      url: https://dev-1p1l3bz6kxwkga5k.us.auth0.com/
      audiences:
        - Fe1ZbPzybfgKmIGs7ShGWJ3jmQVPZdMf
    claimMappings:
      username:
        claim: email
        prefix: "bacchus:"
      groups:
        claim: https://bacchus.io/groups
        prefix: "bacchus:"
