[Interface]
Address = 10.200.0.<control plane number>/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/wg-sgs.key

[Peer]
PublicKey = <tunnelled node public key>
AllowedIPs = 10.200.0.<tunnelled node number>/32
