[Interface]
Address = 10.200.0.<tunnelled node number>/24
PostUp = wg set %i private-key /etc/wireguard/wg-sgs.key

[Peer]
PublicKey = <zest-control-1 public key>
Endpoint = 147.46.91.26:51820
AllowedIPs = 10.200.0.1/32
PersistentKeepalive = 25

[Peer]
PublicKey = <zest-control-2 public key>
Endpoint = 147.46.91.46:51820
AllowedIPs = 10.200.0.2/32
PersistentKeepalive = 25

[Peer]
PublicKey = <zest-control-3 public key>
Endpoint = 147.46.91.49:51820
AllowedIPs = 10.200.0.3/32
PersistentKeepalive = 25
