---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: default
spec:
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: infra
spec:
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: argocd
  name: argocd-server
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - argocd.bacchus.io
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: argocd
  name: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: argocd
  name: dex-auth
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: argocd/dex-auth
  destination:
    create: true
    name: dex-auth
    labels:
      app.kubernetes.io/part-of: argocd
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: argocd
  name: repo-cd-manifests
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: argocd/repo-cd-manifests
  destination:
    create: true
    name: repo-cd-manifests
    labels:
      app.kubernetes.io/part-of: argocd
      argocd.argoproj.io/secret-type: repository
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: argocd
  name: argocd-secret
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: argocd/argocd-secret
  destination:
    create: true
    name: argocd-secret
    labels:
      app.kubernetes.io/part-of: argocd
