---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.51.2
      chart: argo-cd
      helm:
        valueFiles:
          - $values/foundation/argo/argocd/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: foundation/argo/argocd
      directory:
        include: 'resources.yaml'

