resources:
  - core
  - front
  - resources.yaml

configMapGenerator:
  - name: id-db-schema
    files:
      - https://raw.githubusercontent.com/bacchus-snu/id/6a66a1ee17c3fc42ab0d3172e404cb0a158e0402/schema.sql
    options:
      disableNameSuffixHash: true
