auth:
  enablePostgresUser: false
  username: id
  database: id
  existingSecret: id-db-creds
  secretKeys:
    userPasswordKey: password

primary:
  initdb:
    scriptsConfigMap: id-db-schema
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi
