---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: mysql-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: mysql-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://mysql.github.io/mysql-operator/
      targetRevision: 2.3.0
      chart: mysql-operator
      helm:
        valuesObject:
          envs:
            k8sClusterDomain: cluster.local
