---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metrics-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: kube-system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      targetRevision: 3.11.0
      chart: metrics-server
      helm:
        valueFiles:
          - $values/foundation/argo/metrics-server/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
