---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gpu-operator
    server: 'https://147.46.92.213:6443'
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: 23.3.2
    chart: gpu-operator
    helm:
      values: |
        mig:
          strategy: mixed

        toolkit:
          env:
            - name: CONTAINERD_CONFIG
              value: /etc/k0s/containerd.toml
            - name: CONTAINERD_SOCKET
              value: /run/k0s/containerd.sock

        dcgmExporter:
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: kube-prometheus-stack
  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
