---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://147.46.92.213:6443'
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.7.1
    chart: ingress-nginx
    helm:
      values: |
        controller:
          ingressClassResource:
            default: true
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
        config:
          use-forwarded-headers: 'true'
          force-ssl-redirect: 'true'
  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
