---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-openebs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://147.46.92.213:6443'
  source:
    repoURL: 'https://github.com/bacchus-snu/cd-manifests.git'
    targetRevision: HEAD
    path: projects/bentley-openebs
  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
