---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: id-dev
  name: id-db-config
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: db-password
      remoteRef:
        key: /dev/id/config
        property: db-password
    - secretKey: db-admin-password
      remoteRef:
        key: /dev/id/config
        property: db-admin-password
    - secretKey: db-replication-password
      remoteRef:
        key: /dev/id/config
        property: db-replication-password
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: id-db-dev
spec:
  destination:
    namespace: id-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.2
    chart: postgresql
    helm:
      values: |
        auth:
          username: id
          database: id
          existingSecret: id-db-config
          secretKeys:
            userPasswordKey: db-password
            adminPasswordKey: db-admin-password
            replicationPasswordKey: db-replication-password
  project: id-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
