---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  namespace: id-dev
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
    limits:
      storage: 20Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  namespace: id-dev
spec:
  schedule: "0 0 * * *"
  timeZone: Asia/Seoul
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-container
              image: bitnami/kubectl:1.25
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
                limits:
                  memory: 128Mi
              volumeMounts:
                - name: backup-storage
                  mountPath: "/mnt/backup"
              env:
                - name: password
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: id-db-config
              command: ['/bin/bash', '-c', 
                'kubectl exec -i id-db-dev-postgresql-0 -- pg_dump -U id <<<"$password" > /mnt/backup/$(date -Isecond).sql']
          serviceAccountName: backup-job
          restartPolicy: Never
          securityContext:
            fsGroup: 1337
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-job
  namespace: id-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-job
  namespace: id-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: backup-job
