---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: id-front-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: id-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/bacchus-snu/cd-manifests.git'
    path: charts/id-front
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: next
        env:
          - name: HOST
            value: '0.0.0.0'
          - name: PORT
            value: '3000'
          - name: API_BASE
            value: 'http://id-core-dev.id-dev.svc'
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: id-dev.bacchus.io
              paths:
                - path: /
                  pathType: Prefix
  project: id-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
