---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: id-front-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: id
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/bacchus-snu/cd-manifests.git'
    path: charts/id-front
    targetRevision: HEAD
    helm:
      values: |
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: id.snucse.org
              paths:
                - path: /
                  pathType: Prefix
  project: id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
