---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: dexidp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dexidp
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.dexidp.io
    targetRevision: 0.14.1
    chart: dex
    helm:
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 512Mi

        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: auth.bacchus.io
              paths:
                - path: /
                  pathType: Prefix

        envVars:
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dex-google-secret
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-google-secret
                key: GOOGLE_CLIENT_SECRET
          - name: GOOGLE_SERVICE_ACCOUNT
            value: /secret/service-account.json

          - name: DEX_CLIENT_BACCHUS_GRAFANA
            valueFrom:
              secretKeyRef:
                name: dex-client-secrets
                key: bacchus-grafana

        volumes:
          - name: dex-data
            persistentVolumeClaim:
              claimName: dex-data
          - name: dex-google-secret
            secret:
              secretName: dex-google-secret
              items:
                - key: GOOGLE_SERVICE_ACCOUNT
                  path: service-account.json

        volumeMounts:
          - name: dex-data
            mountPath: /data
          - name: dex-google-secret
            mountPath: /secret

        podSecurityContext:
          fsGroup: 1337
        strategy:
          type: Recreate

        config:
          issuer: https://auth.bacchus.io/dex
          storage:
            type: sqlite3
            config:
              file: /data/dex.db

          staticClients:
            - name: Grafana
              id: bacchus-grafana
              redirectURIs:
                - https://dashboard.bacchus.io/login/generic_oauth
              secret: $DEX_CLIENT_BACCHUS_GRAFANA

          connectors:
            - name: Google
              id: google
              type: google
              config:
                issuer: https://accounts.google.com
                clientID: $GOOGLE_CLIENT_ID
                clientSecret: $GOOGLE_CLIENT_SECRET
                redirectURI: https://auth.bacchus.io/dex/callback

                hostedDomains:
                  - bacchus.snucse.org

                serviceAccountFilePath: $GOOGLE_SERVICE_ACCOUNT
                adminEmail: admin@snucse.org

  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: dexidp
  name: dex-google-secret
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: /infra/dexidp/google
  data:
    - secretKey: GOOGLE_SERVICE_ACCOUNT
      remoteRef:
        key: /infra/dexidp/google-service-account
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: dexidp
  name: dex-client-secrets
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  dataFrom:
    - find:
        path: /infra/dexidp/clients/
        name:
          regexp: '.*'
      rewrite:
        - regexp:
            source: /infra/dexidp/clients/(.*)
            target: $1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dexidp
  name: dex-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
