---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: aws-load-balancer-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    targetRevision: 1.4.4
    chart: aws-load-balancer-controller
    helm:
      values: |
        clusterName: bartender
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::642254835236:role/aws-load-balance-controller'
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
