---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: prometheus-operator-crds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dashboard
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-40.2.0
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: dashboard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dashboard
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 40.2.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        defaultRules:
          rules:
            alertmanager: false

        alertmanager:
          enabled: false

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 100Gi
            additionalScrapeConfigs:
            - job_name: 'hardware-lab'
              metrics_path: /metrics
              static_configs:
              - targets: ['147.46.78.190:9100']
                labels:
                  machine_id: '311-2-01'
              - targets: ['147.46.78.191:9100']
                labels:
                  machine_id: '311-2-02'
              - targets: ['147.46.78.192:9100']
                labels:
                  machine_id: '311-2-03'
              - targets: ['147.46.78.193:9100']
                labels:
                  machine_id: '311-2-04'
              - targets: ['147.46.78.194:9100']
                labels:
                  machine_id: '311-2-05'
              - targets: ['147.46.78.195:9100']
                labels:
                  machine_id: '311-2-06'
              - targets: ['147.46.78.196:9100']
                labels:
                  machine_id: '311-2-07'
              - targets: ['147.46.78.197:9100']
                labels:
                  machine_id: '311-2-08'
              - targets: ['147.46.78.198:9100']
                labels:
                  machine_id: '311-2-09'
              - targets: ['147.46.78.199:9100']
                labels:
                  machine_id: '311-2-10'
              - targets: ['147.46.78.200:9100']
                labels:
                  machine_id: '311-2-11'
              - targets: ['147.46.78.201:9100']
                labels:
                  machine_id: '311-2-12'
              - targets: ['147.46.78.202:9100']
                labels:
                  machine_id: '311-2-13'
              - targets: ['147.46.78.203:9100']
                labels:
                  machine_id: '311-2-14'
              - targets: ['147.46.78.204:9100']
                labels:
                  machine_id: '311-2-15'
              - targets: ['147.46.78.205:9100']
                labels:
                  machine_id: '311-2-16'
              - targets: ['147.46.78.206:9100']
                labels:
                  machine_id: '311-2-17'
              - targets: ['147.46.78.207:9100']
                labels:
                  machine_id: '311-2-18'
              - targets: ['147.46.78.208:9100']
                labels:
                  machine_id: '311-2-19'
              - targets: ['147.46.78.209:9100']
                labels:
                  machine_id: '311-2-20'
              - targets: ['147.46.78.210:9100']
                labels:
                  machine_id: '311-2-21'
              - targets: ['147.46.78.211:9100']
                labels:
                  machine_id: '311-2-22'
              - targets: ['147.46.78.212:9100']
                labels:
                  machine_id: '311-2-23'
              - targets: ['147.46.78.213:9100']
                labels:
                  machine_id: '311-2-24'
              - targets: ['147.46.78.214:9100']
                labels:
                  machine_id: '311-2-25'
              - targets: ['147.46.78.215:9100']
                labels:
                  machine_id: '311-2-26'
              - targets: ['147.46.78.216:9100']
                labels:
                  machine_id: '311-2-27'
              - targets: ['147.46.78.217:9100']
                labels:
                  machine_id: '311-2-28'
              - targets: ['147.46.78.218:9100']
                labels:
                  machine_id: '311-2-29'
              - targets: ['147.46.78.219:9100']
                labels:
                  machine_id: '311-2-30'
            - job_name: 'lounge'
              metrics_path: /metrics
              static_configs:
              - targets: ['147.46.127.118:9100']
                labels:
                  machine_id: '314-C01'
              - targets: ['147.46.127.119:9100']
                labels:
                  machine_id: '314-C02'
              - targets: ['147.46.127.120:9100']
                labels:
                  machine_id: '314-C03'
              - targets: ['147.46.127.121:9100']
                labels:
                  machine_id: '314-C04'
              - targets: ['147.46.127.122:9100']
                labels:
                  machine_id: '314-C05'
              - targets: ['147.46.127.123:9100']
                labels:
                  machine_id: '314-C06'
              - targets: ['147.46.127.124:9100']
                labels:
                  machine_id: '314-C07'
              - targets: ['147.46.127.125:9100']
                labels:
                  machine_id: '314-C08'
              - targets: ['147.46.127.126:9100']
                labels:
                  machine_id: '314-C09'
              - targets: ['147.46.127.127:9100']
                labels:
                  machine_id: '314-C10'
            - job_name: 'servers'
              metrics_path: /metrics
              static_configs:
              - targets: ['martini.snucse.org:9100']
                labels:
                  machine_id: 'martini'
              - targets: ['skyy.snucse.org:9100']
                labels:
                  machine_id: 'skyy'
              - targets: ['sherry.snucse.org:9100']
                labels:
                  machine_id: 'sherry'
              - targets: ['oloroso.snucse.org:9100']
                labels:
                  machine_id: 'oloroso'
            - job_name: 'gpu-node-exporter'
              metrics_path: /node-exporter/metrics
              static_configs:
              - targets: ['ferrari.snucse.org:30080']
                labels:
                  machine_id: 'ferrari'
              - targets: ['bentley.snucse.org:30080']
                labels:
                  machine_id: 'bentley'
            - job_name: 'gpu-kube-state-metrics'
              metrics_path: /kube-state/metrics
              static_configs:
              - targets: ['ferrari.snucse.org:30080']
                labels:
                  machine_id: 'ferrari'
              - targets: ['bentley.snucse.org:30080']
                labels:
                  machine_id: 'bentley'
            - job_name: 'gpu-dcgm-exporter'
              metrics_path: /dcgm-exporter/metrics
              static_configs:
              - targets: ['ferrari.snucse.org:30080']
                labels:
                  machine_id: 'ferrari'
              - targets: ['bentley.snucse.org:30080']
                labels:
                  machine_id: 'bentley'

        grafana:
          imageRenderer:
            grafanaProtocol: https

          grafana.ini:
            server:
              domain: dashboard.bacchus.io
              root_url: "https://%(domain)s"

            auth.generic_oauth:
              enabled: true
              allow_sign_up: true
              client_id: bacchus-grafana
              client_secret: '$__file{/etc/secrets/dex-auth/secret}'
              scopes: openid email profile groups
              api_url: https://auth.bacchus.io/dex/userinfo
              auth_url: https://auth.bacchus.io/dex/auth
              token_url: https://auth.bacchus.io/dex/token
              role_attribute_path: contains(groups[*], 'regular-members@bacchus.snucse.org') && 'Editor' || contains(groups[*], 'member@bacchus.snucse.org') && 'Viewer'

          extraSecretMounts:
            - name: dex-auth
              secretName: dex-auth
              mountPath: /etc/secrets/dex-auth
              readOnly: true

          persistence:
            enabled: true
            type: pvc
            size: 20Gi

          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - dashboard.bacchus.io
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/failurePolicy
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: dashboard
  name: dex-auth
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: secret
      remoteRef:
        key: /infra/dexidp/clients/bacchus-grafana
