---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: prometheus-operator-crds
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dashboard
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-40.2.0
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Replace=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: dashboard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dashboard
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 40.2.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        defaultRules:
          rules:
            alertmanager: false

        alertmanager:
          enabled: false

        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 100Gi
            additionalScrapeConfigs:
            - job_name: 'hardware-lab'
              metrics_path: /metrics
              static_configs:
              - targets: ['147.46.78.190:9100']
                labels:
                  machine_id: '311-2-01'
              - targets: ['147.46.78.191:9100']
                labels:
                  machine_id: '311-2-02'
              - targets: ['147.46.78.192:9100']
                labels:
                  machine_id: '311-2-03'
              - targets: ['147.46.78.193:9100']
                labels:
                  machine_id: '311-2-04'
              - targets: ['147.46.78.194:9100']
                labels:
                  machine_id: '311-2-05'
              - targets: ['147.46.78.195:9100']
                labels:
                  machine_id: '311-2-06'
              - targets: ['147.46.78.196:9100']
                labels:
                  machine_id: '311-2-07'
              - targets: ['147.46.78.197:9100']
                labels:
                  machine_id: '311-2-08'
              - targets: ['147.46.78.198:9100']
                labels:
                  machine_id: '311-2-09'
              - targets: ['147.46.78.199:9100']
                labels:
                  machine_id: '311-2-10'
              - targets: ['147.46.78.200:9100']
                labels:
                  machine_id: '311-2-11'
              - targets: ['147.46.78.201:9100']
                labels:
                  machine_id: '311-2-12'
              - targets: ['147.46.78.202:9100']
                labels:
                  machine_id: '311-2-13'
              - targets: ['147.46.78.203:9100']
                labels:
                  machine_id: '311-2-14'
              - targets: ['147.46.78.204:9100']
                labels:
                  machine_id: '311-2-15'
              - targets: ['147.46.78.205:9100']
                labels:
                  machine_id: '311-2-16'
              - targets: ['147.46.78.206:9100']
                labels:
                  machine_id: '311-2-17'
              - targets: ['147.46.78.207:9100']
                labels:
                  machine_id: '311-2-18'
              - targets: ['147.46.78.208:9100']
                labels:
                  machine_id: '311-2-19'
              - targets: ['147.46.78.209:9100']
                labels:
                  machine_id: '311-2-20'
              - targets: ['147.46.78.210:9100']
                labels:
                  machine_id: '311-2-21'
              - targets: ['147.46.78.211:9100']
                labels:
                  machine_id: '311-2-22'
              - targets: ['147.46.78.212:9100']
                labels:
                  machine_id: '311-2-23'
              - targets: ['147.46.78.213:9100']
                labels:
                  machine_id: '311-2-24'
              - targets: ['147.46.78.214:9100']
                labels:
                  machine_id: '311-2-25'
              - targets: ['147.46.78.215:9100']
                labels:
                  machine_id: '311-2-26'
              - targets: ['147.46.78.216:9100']
                labels:
                  machine_id: '311-2-27'
              - targets: ['147.46.78.217:9100']
                labels:
                  machine_id: '311-2-28'
              - targets: ['147.46.78.218:9100']
                labels:
                  machine_id: '311-2-29'
              - targets: ['147.46.78.219:9100']
                labels:
                  machine_id: '311-2-30'
            - job_name: 'lounge'
              metrics_path: /metrics
              static_configs:
              - targets: ['147.46.127.102:9100']
                labels:
                  machine_id: '314-A01'
              - targets: ['147.46.127.103:9100']
                labels:
                  machine_id: '314-A02'
              - targets: ['147.46.127.104:9100']
                labels:
                  machine_id: '314-A03'
              - targets: ['147.46.127.105:9100']
                labels:
                  machine_id: '314-A04'
              - targets: ['147.46.127.106:9100']
                labels:
                  machine_id: '314-A05'
              - targets: ['147.46.127.107:9100']
                labels:
                  machine_id: '314-A06'
              - targets: ['147.46.127.108:9100']
                labels:
                  machine_id: '314-A07'
              - targets: ['147.46.127.109:9100']
                labels:
                  machine_id: '314-A08'
              - targets: ['147.46.127.110:9100']
                labels:
                  machine_id: '314-B01'
              - targets: ['147.46.127.111:9100']
                labels:
                  machine_id: '314-B02'
              - targets: ['147.46.127.112:9100']
                labels:
                  machine_id: '314-B03'
              - targets: ['147.46.127.113:9100']
                labels:
                  machine_id: '314-B04'
              - targets: ['147.46.127.114:9100']
                labels:
                  machine_id: '314-B05'
              - targets: ['147.46.127.115:9100']
                labels:
                  machine_id: '314-B06'
              - targets: ['147.46.127.116:9100']
                labels:
                  machine_id: '314-B07'
              - targets: ['147.46.127.117:9100']
                labels:
                  machine_id: '314-B08'
              - targets: ['147.46.127.118:9100']
                labels:
                  machine_id: '314-C01'
              - targets: ['147.46.127.119:9100']
                labels:
                  machine_id: '314-C02'
              - targets: ['147.46.127.120:9100']
                labels:
                  machine_id: '314-C03'
              - targets: ['147.46.127.121:9100']
                labels:
                  machine_id: '314-C04'
              - targets: ['147.46.127.122:9100']
                labels:
                  machine_id: '314-C05'
              - targets: ['147.46.127.123:9100']
                labels:
                  machine_id: '314-C06'
              - targets: ['147.46.127.124:9100']
                labels:
                  machine_id: '314-C07'
              - targets: ['147.46.127.125:9100']
                labels:
                  machine_id: '314-C08'
              - targets: ['147.46.127.126:9100']
                labels:
                  machine_id: '314-C09'
              - targets: ['147.46.127.127:9100']
                labels:
                  machine_id: '314-C10'
              - targets: ['147.46.127.128:9100']
                labels:
                  machine_id: '314-C11'
              - targets: ['147.46.127.129:9100']
                labels:
                  machine_id: '314-C12'
              - targets: ['147.46.127.130:9100']
                labels:
                  machine_id: '314-C13'
              - targets: ['147.46.127.131:9100']
                labels:
                  machine_id: '314-C14'
            - job_name: 'servers'
              metrics_path: /metrics
              static_configs:
              - targets: ['martini.snucse.org:9100']
                labels:
                  machine_id: 'martini'
              - targets: ['skyy.snucse.org:9100']
                labels:
                  machine_id: 'skyy'
              - targets: ['sherry.snucse.org:9100']
                labels:
                  machine_id: 'sherry'
              - targets: ['oloroso.snucse.org:9100']
                labels:
                  machine_id: 'oloroso'

        grafana:
          imageRenderer:
            grafanaProtocol: https

          grafana.ini:
            server:
              domain: dashboard.bacchus.io
              root_url: "https://%(domain)s"
            auth.github:
              enabled: true
              allow_sign_up: true
              scopes: user:email,read:org
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              allowed_organizations: bacchus-snu
              client_id: '1d692134938f08d650f4'
              client_secret: '$__file{/etc/secrets/github-oauth/secret}'

          extraSecretMounts:
          - name: github-oauth-mount
            secretName: github-oauth
            defaultMode: 0440
            mountPath: /etc/secrets/github-oauth
            readOnly: true

          persistence:
            enabled: true
            type: pvc
            size: 20Gi

          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - dashboard.bacchus.io
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: "MutatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: "admissionregistration.k8s.io"
      kind: "ValidatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/failurePolicy
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: dashboard
  name: github-oauth
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: secret
      remoteRef:
        key: /infra/grafana/config
        property: GITHUB_OAUTH_CLIENT_SECRET
