---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bacchus-bridge
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bacchus-bridge
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/bacchus-snu/cd-manifests.git
    targetRevision: HEAD
    path: apps/bacchus-bridge
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
