---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: loki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dashboard
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.8.4
    chart: loki-stack
    helm:
      values: |
        loki:
          persistence:
            enabled: true
            size: 100Gi
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
