---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: cluster-autoscaler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes.github.io/autoscaler'
    targetRevision: 9.21.0
    chart: cluster-autoscaler
    helm:
      values: |
        awsRegion: ap-northeast-2
        autoDiscovery:
          clusterName: bartender
        extraArgs:
          balance-similar-node-groups: true
        rbac:
          serviceAccount:
            name: cluster-autoscaler
            annotations:
              eks.amazonaws.com/role-arn: 'arn:aws:iam::642254835236:role/cluster-autoscaler'
        
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
