---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: snapshot-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://piraeus.io/helm-charts'
    targetRevision: 1.8.1
    chart: snapshot-controller
    helm:
      values: |
        serviceMonitor:
          create: true
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi
driver: ebs.csi.aws.com
deletionPolicy: Delete
