---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.6.1
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::642254835236:role/external-secrets'
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
