---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns'
    targetRevision: 1.11.0
    chart: external-dns
    helm:
      values: |
        sources:
        - ingress
        domainFilters:
        - bacchus.io
        provider: cloudflare
        policy: sync
        extraArgs:
        - --cloudflare-proxied
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: CF_API_TOKEN
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: external-dns
  name: cloudflare
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: /infra/externaldns/config
        property: CF_API_TOKEN
