---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argo
  name: testing
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Testing applications
  sourceRepos:
    - https://github.com/bacchus-snu/cd-manifests.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: testing
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: v1
kind: Namespace
metadata:
  name: testing
