---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: bacchus-sgs-registry
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: bacchus-sgs-registry
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://helm.goharbor.io
      targetRevision: 1.18.0
      chart: harbor
      helm:
        valueFiles:
          - $values/argocd/waiter/bacchus-sgs-registry/values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/bacchus-sgs-registry
      directory:
        include: 'resources.yaml'
