---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cloudstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cloudstack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        # the management server mounts NFS secondary storage to seed system VM templates
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: v1.29
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: v1.29
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: v1.29
  sources:
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      path: argocd/waiter/cloudstack
      kustomize: {}
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 11.1.20
      chart: mysql
      helm:
        valueFiles:
          - $values/argocd/waiter/cloudstack/mysql-values.yaml
    - repoURL: https://github.com/bacchus-snu/cd-manifests.git
      targetRevision: main
      ref: values
