apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: cilium-system
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://helm.cilium.io/
      targetRevision: 1.14.3
      chart: cilium
      helm:
        values: |-
          # ref: https://www.talos.dev/v1.5/kubernetes-guides/network/deploying-cilium/
          ipam:
            mode: kubernetes
          cgroup:
            autoMount:
              enabled: false
            hostRoot: /sys/fs/cgroup
          securityContext:
            capabilities:
              cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
              ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]

          # replace kube-proxy
          kubeProxyReplacement: true
          k8sServiceHost: localhost
          k8sServicePort: 7445

          # enable hubble
          hubble:
            relay:
              enabled: true
            ui:
              enabled: true

          # enable gateway
          gatewayAPI:
            enabled: true
