apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.48.0
      chart: argo-cd
      helm:
        values: |-
          dex:
            enabled: false
          configs:
            cm:
              admin.enabled: false
              oidc.config: |
                name: Bacchus Dex
                issuer: https://auth.bacchus.io/dex
                clientID: bacchus-argocd
                clientSecret: $dex-auth:secret
              url: https://argocd.bacchus.io
            params:
              server.insecure: true
            rbac:
              policy.csv: |
                g, regular-members@bacchus.snucse.org, role:admin
              policy.default: role:readonly
