apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: cert-manager
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.13.1
      chart: cert-manager
      helm:
        values: |-
          installCRDs: true
          enableCertificateOwnerRef: true
          resources:
             requests:
               cpu: 100m
               memory: 128Mi
             limits:
               cpu: 100m
               memory: 128Mi
          extraArgs:
            - --feature-gates=ExperimentalGatewayAPISupport=true
