---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy-http
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: http
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 80
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            # remove Server header
            remove:
              - Server
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-cse
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 443
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            # remove Server header
            remove:
              - Server
---
apiVersion: v1
kind: Service
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    app.kubernetes.io/name: cse-proxy
    app.kubernetes.io/instance: cse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cse-proxy
      app.kubernetes.io/instance: cse-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cse-proxy
        app.kubernetes.io/instance: cse-proxy
    spec:
      hostAliases:
        - hostnames:
            - cse.snu.ac.kr
          ip: 10.91.1.1
      serviceAccountName: cse-proxy
      initContainers:
        - name: envoy-patch
          image: bitnami/kubectl:latest
          restartPolicy: Always # sidecar
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          command:
            # set serverHeaderTransformation=PASS_THROUGH
            - /bin/bash
            - -c
            - |
                set -eu
                while true; do
                  sleep 10
                  check=$(kubectl get \
                    -n cilium-system \
                    ciliumenvoyconfigs.cilium.io/cilium-gateway-web-gateway \
                    -ojsonpath='{$.spec.resources[0].filterChains[0].filters[0].typedConfig.serverHeaderTransformation}')
                  [[ "$check" = "PASS_THROUGH" ]] && continue
                  kubectl patch \
                    -n cilium-system \
                    --type=json \
                    ciliumenvoyconfigs.cilium.io/cilium-gateway-web-gateway \
                    -p '[{"op":"add","path":"/spec/resources/0/filterChains/0/filters/0/typedConfig/serverHeaderTransformation","value":"PASS_THROUGH"},{"op":"add","path":"/spec/resources/0/filterChains/2/filters/0/typedConfig/serverHeaderTransformation","value":"PASS_THROUGH"}]'
                done
      containers:
        - name: app-http
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --access-log
            - --change-host-header
            - --from=:8080
            - --to=http://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        - name: app-https
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --access-log
            - --change-host-header
            - --from=:8443
            - --to=https://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cse-proxy-patch
rules:
  - apiGroups:
      - cilium.io
    resources:
      - ciliumenvoyconfigs
    verbs:
      - get
      - patch
    resourceNames:
      - cilium-gateway-web-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cse-proxy-patch
subjects:
  - kind: ServiceAccount
    namespace: cse-proxy
    name: cse-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cse-proxy-patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cse-proxy
  name: cse-proxy
