---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy-cse
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-cse
    - namespace: cilium-system
      name: web-gateway
      sectionName: http
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy-csereal-prod
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-bacchus-io
    - namespace: cilium-system
      name: web-gateway
      sectionName: http
  hostnames:
    - csereal-prod.bacchus.io
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 81
---
apiVersion: v1
kind: Service
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    app.kubernetes.io/name: cse-proxy
    app.kubernetes.io/instance: cse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-alt
      port: 81
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cse-proxy
      app.kubernetes.io/instance: cse-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cse-proxy
        app.kubernetes.io/instance: cse-proxy
    spec:
      hostAliases:
        - hostnames:
            - cse.snu.ac.kr
          ip: 147.46.242.104
        - hostnames:
            - csereal-prod.bacchus.io
          ip: 10.91.1.1
      containers:
        - name: cse
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --from=http://cse.snu.ac.kr:8080
            - --to=https://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        - name: csereal-prod
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --from=http://csereal-prod.bacchus.io:8081
            - --to=http://csereal-prod.bacchus.io
          ports:
            - name: http
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
