---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy-http
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: http
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-cse
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 443
---
apiVersion: v1
kind: Service
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    app.kubernetes.io/name: cse-proxy
    app.kubernetes.io/instance: cse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https-alt
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    app.kubernetes.io/name: cse-proxy
    app.kubernetes.io/instance: cse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cse-proxy
      app.kubernetes.io/instance: cse-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cse-proxy
        app.kubernetes.io/instance: cse-proxy
    spec:
      hostAliases:
        - hostnames:
            - csereal-prod.bacchus.io
          ip: 10.91.1.1
      containers:
        - name: app-http
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --access-log
            - --change-host-header
            - --from=:8080
            - --to=http://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              port: 8080
          readinessProbe:
            httpGet:
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        - name: app-https
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --access-log
            - --change-host-header
            - --from=:8443
            - --to=https://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8443
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              port: 8443
          readinessProbe:
            httpGet:
              port: 8443
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
