---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: cse-proxy
  name: cse-proxy
  annotations:
    external-dns.alpha.kubernetes.io/exclude: 'true'
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
  hostnames:
    - cse.snu.ac.kr
  rules:
    - backendRefs:
        - name: cse-proxy
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    app.kubernetes.io/name: cse-proxy
    app.kubernetes.io/instance: cse-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cse-proxy
  name: cse-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cse-proxy
      app.kubernetes.io/instance: cse-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cse-proxy
        app.kubernetes.io/instance: cse-proxy
    spec:
      hostAliases:
        - hostnames:
            - cse.snu.ac.kr
          ip: 147.46.242.104
      containers:
        - name: app
          image: 'caddy:2-alpine'
          args:
            - caddy
            - reverse-proxy
            - --from=http://cse.snu.ac.kr:8080
            - --to=https://cse.snu.ac.kr
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
