---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: rbd
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: 6153aaf2-8844-4257-a269-225933b5fb4a
  pool: kubernetes
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/snapshotter-secret-name:  csi-rbd-secret
