{
 "title": "SGS Resources",
 "tags": [ "GPU" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(sgs:node_resource:capacity,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{node=\"$node\"} - node_boot_time_seconds{node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "max(node_uname_info{node=\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sgs:node_resource:capacity{node=\"$node\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sgs:node_resource:capacity{node=\"$node\"} - sgs:node_resource:unallocated{node=\"$node\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Unallocated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sgs:node_resource:unallocated{node=\"$node\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GPU" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:allocated{node=\"$node\", resource=\"nvidia_com_gpu\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:allocated{node=\"$node\", resource=\"cpu\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:allocated{node=\"$node\", resource=\"memory\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "GPU" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:used{node=\"$node\", resource=\"nvidia_com_gpu\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:used{node=\"$node\", resource=\"cpu\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sgs:node_namespace_resource:used{node=\"$node\", resource=\"memory\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Cumulative Resource Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum_over_time(sgs:node_namespace_resource:used{node=\"$node\"}[$__range:1m]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Resource Over-Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum_over_time((\n    (sgs:node_namespace_resource:allocated{node=\"$node\"} > 0)\n        -\n    sgs:node_namespace_resource:used{node=\"$node\"}\n)[$__range:1m]) / 60 > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods (All Nodes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "count(kube_pod_status_scheduled{condition=\"false\", namespace=~\"ws-.*\"} == 1) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Over-Allocation Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 }
  }
 ]
}