defaultVaultConnection:
  enabled: true
  address: http://vault.vault.svc.cluster.local:8200

controller:
  kubeRbacProxy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi

  manager:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
