resources:
  - statefulset.yaml
  - httproute.yaml
  - rbac.yaml
  - secret.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: wg-access-server
      app.kubernetes.io/instance: bacchus-vpn
    includeSelectors: true

images:
  - name: alpine
    newTag: '3.21'
  - name: kubectl
    newName: bitnamilegacy/kubectl
    newTag: '1.31'
  - name: wg-access-server
    newName: ghcr.io/freifunkmuc/wg-access-server
    newTag: v0.13.0
