---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bacchus-vpn-config
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: secret
  path: bacchus-vpn/config
  destination:
    create: true
    name: bacchus-vpn-config
