apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bacchus-vpn
spec:
  serviceName: bacchus-vpn-headless
  volumeClaimTemplates:
    - metadata:
        name: bacchus-vpn-data
      spec:
        accessModes:
          - ReadWriteOncePod
        resources:
          requests:
            storage: 1Gi
  template:
    spec:
      initContainers:
        - name: network-setup
          image: alpine # replaced by kustomize
          command:
            - sh
            - -c
            - |
                # enable ip forwarding
                sysctl -w net.ipv4.ip_forward=1
                # clamp MSS to PMTU
                apk add iptables
                iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
          securityContext:
            privileged: true
        - name: envoy-patch
          image: kubectl
          restartPolicy: Always # sidecar
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          command:
            # patch cilium-managed envoyconfig to remove grpc_web filter
            - /bin/bash
            - -c
            - |
                set -eu
                while true; do
                  sleep 10
                  first_filter=$(kubectl get \
                    -n cilium-system \
                    ciliumenvoyconfigs.cilium.io/cilium-gateway-web-gateway \
                    -ojsonpath='{$.spec.resources[0].filterChains[0].filters[0].typedConfig.httpFilters[0].name}')
                  [[ "$first_filter" = "envoy.filters.http.grpc_web" ]] || continue
                  kubectl patch \
                    -n cilium-system \
                    --type=json \
                    ciliumenvoyconfigs.cilium.io/cilium-gateway-web-gateway \
                    -p '[{"op":"remove","path":"/spec/resources/0/filterChains/0/filters/0/typedConfig/httpFilters/0"},{"op":"remove","path":"/spec/resources/0/filterChains/1/filters/0/typedConfig/httpFilters/0"}]'
                done
      containers:
        - name: app
          image: wg-access-server # replaced by kustomize
          ports:
            - name: http
              containerPort: 8000
            - protocol: UDP
              containerPort: 51820
          env:
            - name: WG_CONFIG
              value: /config.yaml
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: config
              subPath: config.yaml
              mountPath: /config.yaml
              readOnly: true
            - name: bacchus-vpn-data
              mountPath: /data
          readinessProbe:
            httpGet:
              port: http
              path: /health
          livenessProbe:
            httpGet:
              port: http
              path: /health
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: bacchus-vpn
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: config
          secret:
            secretName: bacchus-vpn-config
