apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snucse-api.fullname" . }}
  labels:
    {{- include "snucse-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snucse-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snucse-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snucse-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: secret
              mountPath: /app/config/secrets.yml
              subPath: 'secrets.yml'
            - name: config
              mountPath: /app/config/database.yml
              subPath: 'database.yml'
            - name: config
              mountPath: /app/config/elasticsearch.yml
              subPath: 'elasticsearch.yml'
            - name: config
              mountPath: /app/config/redis.yml
              subPath: 'redis.yml'
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ .Values.config.secret.name }}
            optional: false
            defaultMode: 0400
        - name: config
          configMap:
            name: {{ .Values.config.cm.name | default (include "snucse-api.defaultConfigMapName" .) }}
            optional: false
            defaultMode: 0400
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if not .Values.config.cm.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snucse-api.defaultConfigMapName" . }}
  labels:
    {{- include "snucse-api.labels" . | nindent 4 }}
data:
  {{- with .Values.config.cm }}
  database.yml: {{ .database | quote }}
  elasticsearch.yml: {{ .elasticsearch | quote }}
  redis.yml: {{ .redis | quote }}
  {{- end }}
{{- end }}
