apiVersion: v1
kind: Service
metadata:
  name: {{ include "snucse-api.fullname" . }}
  labels:
    {{- include "snucse-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    {{- include "snucse-api.selectorLabels" . | nindent 4 }}
