---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: bacchus-sgs-dev
  name: bacchus-sgs-dev-db
spec:
  instances: 1
  storage:
    size: 8Gi
    storageClass: rbd
  bootstrap:
    initdb:
      database: bacchus-sgs
      owner: bacchus-sgs
      secret:
        name: bacchus-sgs-dev-db-creds
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
